#!/usr/bin/env bash
# Activate the production-auth block in mosquitto.conf.
#
# Prereqs (the script will refuse to flip if any are missing):
#   - /mosquitto/config/passwd exists and is non-empty
#   - /mosquitto/config/acl.conf exists
#   - Mission Control has been redeployed with the MqttBridge auth path
#     (clientConfig.mqttViewerPassword consumed by MqttBridge.tsx +
#     CommandFleetMqttBridge.tsx; check by viewing the deployed bundle).
#
# Run on the broker host:
#   ./activate-auth.sh
#
# To roll back, use deactivate-auth.sh in the same directory.

set -euo pipefail

MOSQ_CONF="${MOSQ_CONF:-/opt/relay/mosquitto/mosquitto.conf}"
PASSWD_PATH="${PASSWD_PATH:-/opt/relay/mosquitto/passwd}"
ACL_PATH="${ACL_PATH:-/opt/relay/mosquitto/acl.conf}"
BROKER_CONTAINER="${BROKER_CONTAINER:-relay-mosquitto-1}"

if [[ ! -s "${PASSWD_PATH}" ]]; then
  echo "activate-auth: ${PASSWD_PATH} missing or empty — run regenerate-passwd.sh first" >&2
  exit 1
fi
if [[ ! -f "${ACL_PATH}" ]]; then
  echo "activate-auth: ${ACL_PATH} missing — run regenerate-passwd.sh first" >&2
  exit 1
fi

stamp="$(date +%s)"
cp -p "${MOSQ_CONF}" "${MOSQ_CONF}.bak.${stamp}"

cat > "${MOSQ_CONF}" <<'CONF'
# Mosquitto broker config — PRODUCTION (auth + ACL enforced).
# Generated by activate-auth.sh. Roll back via deactivate-auth.sh.

listener 1883
listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file      /mosquitto/config/acl.conf
persistence true
persistence_location /mosquitto/data/
autosave_interval 1800
CONF

# SIGHUP the broker so it reloads config without dropping current sessions
# that re-auth successfully. Anonymous sessions will be dropped on next
# message and reconnect with credentials.
docker exec "${BROKER_CONTAINER}" sh -c 'kill -HUP 1' 2>/dev/null || true

# Brief health check.
sleep 1
if docker ps --filter "name=${BROKER_CONTAINER}" --format "{{.Status}}" | grep -q "Up"; then
  echo "activate-auth: production block active. Backup at ${MOSQ_CONF}.bak.${stamp}"
  echo "Watch: docker logs -f ${BROKER_CONTAINER}"
else
  echo "activate-auth: broker is NOT running after flip. Check logs:" >&2
  docker logs --tail 30 "${BROKER_CONTAINER}" >&2
  exit 1
fi
