#!/usr/bin/env bash
# Regenerate /opt/relay/mosquitto/passwd and /opt/relay/mosquitto/acl.conf
# from paired devices in Convex.
#
# Reads CONVEX_HTTP_URL, MQTT_AUTH_RELAY_SECRET, and BRIDGE_MQTT_PASSWORD
# (or MQTT_PASSWORD) from the broker host's environment (typically
# /opt/relay/.env). Pulls the device_id / apiKey pair list from the
# /admin/mqtt-auth-entries httpAction (Bearer-token gated by
# MQTT_AUTH_RELAY_SECRET) and rebuilds both files, then SIGHUPs the broker.
#
# Writes BOTH username conventions per device:
#   - <device_id>            (canonical; agents on current firmware)
#   - ados-<device_id>       (legacy; bench drones still on old firmware)
# Both entries hash the same apiKey. Once all agents are upgraded to the
# canonical username, set DROP_LEGACY_USERNAMES=1 to stop emitting the
# `ados-<id>` rows.
#
# Safe to run from cron. Idempotent. Atomic-swap on success.

set -euo pipefail

CONVEX_HTTP_URL="${CONVEX_HTTP_URL:-https://convex-site.altnautica.com}"
RELAY_SECRET="${MQTT_AUTH_RELAY_SECRET:-}"
BRIDGE_USER="${BRIDGE_MQTT_USERNAME:-ados}"
BRIDGE_PASS="${BRIDGE_MQTT_PASSWORD:-${MQTT_PASSWORD:-}}"
VIEWER_USER="${MQTT_VIEWER_USERNAME:-gcs-viewer}"
VIEWER_PASS="${MQTT_VIEWER_PASSWORD:-}"
PASSWD_PATH="${PASSWD_PATH:-/opt/relay/mosquitto/passwd}"
ACL_PATH="${ACL_PATH:-/opt/relay/mosquitto/acl.conf}"
BROKER_CONTAINER="${BROKER_CONTAINER:-relay-mosquitto-1}"
DROP_LEGACY_USERNAMES="${DROP_LEGACY_USERNAMES:-0}"

if [[ -z "${RELAY_SECRET}" ]]; then
  echo "regenerate-passwd: MQTT_AUTH_RELAY_SECRET not set; aborting" >&2
  exit 1
fi
if [[ -z "${BRIDGE_PASS}" ]]; then
  echo "regenerate-passwd: BRIDGE_MQTT_PASSWORD (or MQTT_PASSWORD) not set; aborting" >&2
  exit 1
fi
if [[ -z "${VIEWER_PASS}" ]]; then
  echo "regenerate-passwd: MQTT_VIEWER_PASSWORD not set; aborting" >&2
  exit 1
fi

response=$(curl -fsS \
  -H "Authorization: Bearer ${RELAY_SECRET}" \
  "${CONVEX_HTTP_URL}/admin/mqtt-auth-entries")

entries_count=$(printf '%s' "${response}" | jq -r '.entries | length')
if [[ -z "${entries_count}" || "${entries_count}" == "null" ]]; then
  echo "regenerate-passwd: malformed response from Convex: ${response}" >&2
  exit 1
fi

# Build passwd inside the broker container at a staging path.
STAGING_PASSWD="/tmp/.mqtt-passwd-stage"
docker exec "${BROKER_CONTAINER}" sh -c \
  "rm -f '${STAGING_PASSWD}' && touch '${STAGING_PASSWD}' && chmod 600 '${STAGING_PASSWD}'"

# Build acl.conf on the host (no mosquitto-specific tooling needed for ACL).
host_acl_staging="$(mktemp --tmpdir mqtt-acl.XXXXXX)"
chmod 644 "${host_acl_staging}"

cat > "${host_acl_staging}" <<'ACL_HEADER'
# Mosquitto ACL for the ADOS cloud relay.
#
# AUTO-GENERATED by regenerate-passwd.sh. Do not edit by hand; changes will
# be overwritten on the next sync. The static `acl.conf` shipped in the
# ADOSMissionControl repo at tools/mqtt-bridge/deploy/acl.conf is the
# documented policy; this file is the materialized per-device version.
#
# Format per device:
#   user <username>
#   topic readwrite ados/<device_id>/#
#
# Username is either the bare device_id (current firmware) or
# `ados-<device_id>` (legacy firmware); both grant the same topic subtree.

ACL_HEADER

# Bridge service account: read-only across all `ados/+/...` topics.
cat >> "${host_acl_staging}" <<ACL_BRIDGE
user ${BRIDGE_USER}
topic read ados/#

# GCS browser sessions: read-only across all `ados/+/...` topics. Password is
# published via the public Convex clientConfig query and is intentionally
# shared by every browser session. Protect telemetry beyond that via TLS +
# Cloudflare Tunnel; do NOT grant write access here.
user ${VIEWER_USER}
topic read ados/#

ACL_BRIDGE

# Iterate device list, write to both passwd (via mosquitto_passwd inside
# container) and acl.conf (plain text on host).
printf '%s' "${response}" \
  | jq -r '.entries[] | "\(.username)\t\(.apiKey)"' \
  | while IFS=$'\t' read -r device_id apikey; do
      [[ -z "${device_id}" || -z "${apikey}" ]] && continue

      # passwd: canonical username == device_id
      docker exec "${BROKER_CONTAINER}" \
        mosquitto_passwd -b "${STAGING_PASSWD}" "${device_id}" "${apikey}"

      # acl.conf: canonical
      cat >> "${host_acl_staging}" <<ACL_DEVICE
user ${device_id}
topic readwrite ados/${device_id}/#

ACL_DEVICE

      if [[ "${DROP_LEGACY_USERNAMES}" != "1" ]]; then
        # passwd: legacy ados-<device_id>
        docker exec "${BROKER_CONTAINER}" \
          mosquitto_passwd -b "${STAGING_PASSWD}" "ados-${device_id}" "${apikey}"

        # acl.conf: legacy, same topic subtree
        cat >> "${host_acl_staging}" <<ACL_LEGACY
user ados-${device_id}
topic readwrite ados/${device_id}/#

ACL_LEGACY
      fi
    done

# Bridge service account in passwd.
docker exec "${BROKER_CONTAINER}" \
  mosquitto_passwd -b "${STAGING_PASSWD}" "${BRIDGE_USER}" "${BRIDGE_PASS}"

# GCS viewer service account in passwd.
docker exec "${BROKER_CONTAINER}" \
  mosquitto_passwd -b "${STAGING_PASSWD}" "${VIEWER_USER}" "${VIEWER_PASS}"

# Copy passwd out of container, atomic-rename into place on host.
host_passwd_staging="$(mktemp --tmpdir mqtt-passwd.XXXXXX)"
chmod 600 "${host_passwd_staging}"
docker exec "${BROKER_CONTAINER}" /bin/cat "${STAGING_PASSWD}" > "${host_passwd_staging}"
docker exec "${BROKER_CONTAINER}" rm -f "${STAGING_PASSWD}"

mv -f "${host_passwd_staging}" "${PASSWD_PATH}"
# Mosquitto inside the container runs as uid 1883; the host-side file must
# be readable by that uid. 640 means owner-read/group-read, others-none.
chown 1883:1883 "${PASSWD_PATH}"
chmod 640 "${PASSWD_PATH}"

mv -f "${host_acl_staging}" "${ACL_PATH}"
chown 1883:1883 "${ACL_PATH}"
chmod 640 "${ACL_PATH}"

# Reload the broker without dropping connections.
docker exec "${BROKER_CONTAINER}" sh -c 'kill -HUP 1' 2>/dev/null || true

echo "regenerate-passwd: wrote ${PASSWD_PATH} + ${ACL_PATH} (${entries_count} devices + bridge + viewer)"
